### PR TITLE
Mapsforge 0.21.0, new parameter "line-scale" and other optimizations

### PR DESCRIPTION
**Pull request by JFritzle**

### CODE REVIEW

**Comment by nono303** [comment]
Hi @ JFritzle,
Thx for this PR! My 2 cents:
1. https://github.com/telemaxx/mapsforgesrv/pull/57/commits/0fe93eacd2b697834e4c58976ea0dd638b8c8872
`jettyVersion = '12.0.7'` might not be good as latest `org.eclipse.jetty.http2:http2-server` is 11.0.20 (cf. https://mvnrepository.com/artifact/org.eclipse.jetty.http2/http2-server)
also, you can set `'+'` for deps without version constraints (for me: all except jetty cf. https://github.com/nono303/mapsforgesrv/blob/master/mapsforgesrv/build.gradle) 

2. https://github.com/telemaxx/mapsforgesrv/pull/57/commits/e49e381d84c9de4230a899d776893187382a7204
You can use `for /r %%f in (marlin*.jar) do (set jarmarlin=%%~nxf)` and replace `marlin-0.9.4.8-Unsafe-OpenJDK11.jar` by `%jarmarlin%` to avoid updating marlin version in launcher...

Fyi, here is my launcher (It remind me that I have to ask community if my `sun.java2d` params are really useful… If you have some inputs I'll take the ;)

```
@echo off
cd /D %~dp0..
set J2D_TRACE_LEVEL=4
SET ymdhis=%date:~-4,4%-%date:~-10,2%-%date:~-7,2%_%time:~0,2%-%time:~3,2%-%time:~6,2%
SET ymdhis=%ymdhis: =0%
for /r %%f in (mapsforgesrv*.jar) do (set jarmapsforge=%%~nxf)
for /r %%f in (marlin*.jar) do (set jarmarlin=%%~nxf)
	REM -Xmx2048m minimun (under: java.lang.OutOfMemoryError: Java heap space)
	REM
	REM java2d
	REM	* log debug:	-Dsun.java2d.trace=timestamp,log,count,out:logs\java2d.%ymdhis%.log ^
	REM	* params	https://www.oracle.com/java/technologies/graphics-performance-improvements.html
	REM	* guide		https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html
	REM marlin renderer
	REM	* params	https://github.com/bourgesl/marlin-renderer/wiki/Tuning-options
@echo on
c:\serveur\openjdk\bin\java.exe ^
--patch-module java.desktop=libs\%jarmarlin% ^
-Xlog:gc:logs\%1-gc.%ymdhis%.log:time,level,tags ^
-Xmx2048m ^
-Xms64m ^
-Dsun.java2d.opengl=true ^
-Dsun.java2d.accthreshold=0 ^
-Dsun.java2d.d3d=false ^
-Dsun.java2d.noddraw=true ^
-Dsun.java2d.translaccel=true ^
-Dsun.java2d.ddforcevram=true ^
-Dsun.java2d.ddscale=true ^
-Dsun.java2d.ddoffscreen=false ^
-Dsun.java2d.renderer.log=true ^
-Dsun.java2d.renderer.useLogger=true ^
-Dsun.java2d.renderer.profile=speed ^
-Dsun.java2d.renderer.useThreadLocal=true ^
-Dsun.java2d.renderer.useFastMath=true ^
-Dsun.java2d.render.bufferSize=65536 ^
-Dsun.java2d.renderer.pixelWidth=256 ^
-Dsun.java2d.renderer.pixelHeight=256 ^
-Dawt.useSystemAAFontSettings=on ^
-jar libs\%jarmapsforge% ^
-c config\%1.properties

```

**Comment by JFritzle** [comment]
Hi @nono303,

thanks for your comments.

1. While updating jettyVersion to '12.0.7' in build.gradle yesterday evening, site https://mvnrepository.com/artifact/org.eclipse.jetty.http2/http2-server was still showing that version as latest. Looking at same site today, all versions '12.\*.\*' have disappeared as if by magic.   
I have reverted version to '11.0.20'. Further on as proposed, I have set '+' for deps without version constraints.
2. Because the launcher script was not initiated by me nor is maintained by me, I have only replaced marlin renderer version by current.  
Btw, in my environment I have multiple mapsforgesrv*.jar files as well as multiple marlin*.jar files in the same folder. Because mapsforgesrv*.jar file and marlin*.jar file have to be selected matching the Java version used, your algorithm is not suitable for me.

**Comment by telemaxx** [comment]
This time i also checked the generated classes and it was ok:

pi@filesrv:~/BTSync/Exchange/mapsforgesrv-fatjar/com/telemaxx/mapsforgesrv$ file *.class
DummyCache.class:                                    compiled Java class data, version 55.0 (Java SE 11)
MapsforgeConfig$1.class:                             compiled Java class data, version 55.0 (Java SE 11)
MapsforgeConfig.class:                               compiled Java class data, version 55.0 (Java SE 11)
MapsforgeHandler$1.class:                            compiled Java class data, version 55.0 (Java SE 11)
MapsforgeHandler$MyResponseBufferOutputStream.class: compiled Java class data, version 55.0 (Java SE 11)
MapsforgeHandler$MyTileBasedLabelStore.class:        compiled Java class data, version 55.0 (Java SE 11)
MapsforgeHandler.class:                              compiled Java class data, version 55.0 (Java SE 11)
MapsforgeSrv.class:                                  compiled Java class data, version 55.0 (Java SE 11)
MapsforgeStyleParser.class:                          compiled Java class data, version 55.0 (Java SE 11)
Style.class:                                         compiled Java class data, version 55.0 (Java SE 11)
pi@filesrv:~/BTSync/Exchange/mapsforgesrv-fatjar/com/telemaxx/mapsforgesrv$

**Comment by telemaxx** [comment]
@nono303 @JFritzle : thanks for the help!

**Comment by nono303** [comment]
All sounds good for me!
For the state of art...
```diff
diff --git "a/mapsforgesrv/build.gradle" "b/mapsforgesrv/build.gradle"
index eaeef59..e4fc588 100644

--- "a/mapsforgesrv/build.gradle"
+++ "b/mapsforgesrv/build.gradle"

@@ -37,7 +36,7 @@ dependencies {
     implementation "org.mapsforge:mapsforge-core:${mapsforgeVersion}"
     implementation "org.mapsforge:mapsforge-map:${mapsforgeVersion}"
     implementation "org.mapsforge:mapsforge-map-reader:${mapsforgeVersion}"
-    implementation "org.mapsforge:mapsforge-themes:${mapsforgeVersion}"
+    runtimeOnly "org.mapsforge:mapsforge-themes:${mapsforgeVersion}"
     implementation "org.mapsforge:mapsforge-map-awt:${mapsforgeVersion}"
 //  implementation "org.mapsforge:mapsforge-poi-awt:${mapsforgeVersion}"
 //  implementation "org.mapsforge:mapsforge-poi:${mapsforgeVersion}"

```

**Pull request merged**
