### PR TITLE
style: Revert IDE settings to java 11

### PR DESCRIPTION
**Pull request by nono303**

### CODE REVIEW

**Comment by nono303** [comment]
Hi @telemaxx,
> https://github.com/telemaxx/mapsforgesrv/pull/63#issuecomment-2140114857  

Just reverted all IDE settings to java 11.
As said, it might be better to exclude them from tracked file in the next release, I let you see

https://github.com/telemaxx/mapsforgesrv/pull/64/commits/b93119c6f4538291542c4df75896a6428d523f14 is a quick memory improvement without any other change

**Comment by telemaxx** [comment]
Now we coming closer.

but still some errors:

grafik

grafik

for unknown reason this line is ignored:
    `implementation "org.eclipse.jetty:jetty-xml:${jettyVersion}"`

but the line seems to be correct

i am on java17, is this a problem? Eclipse should use his own java, correct.

**Comment by nono303** [comment]
I've tried to import **from scratch** my branch as an eclispse gradle project and I was also faced to the same issue.
Before reopening a PR, could you try to do the same on https://github.com/nono303/mapsforgesrv/tree/styles

> i am on java17, is this a problem?

No
> Eclipse should use his own java. correct?

Yes but it was forced to 11.
I bypassed it on https://github.com/nono303/mapsforgesrv/commit/7fb6901c353851f55169086e484038739282007f
> for unknown reason this line is ignored:

because they was classpath lib entries failing which blocked gradle dependencies refresh, as I understand https://github.com/nono303/mapsforgesrv/commit/8a18591fba1819dd45e1e43271f0ac9114b7325b

**Comment by telemaxx** [comment]
i did some tests with a new eclipse workspace.
because i am happy that eclipse is currently running the project(the master branch)
Sometimes eclipse making me crazy.

I tried to import 4 ways, always getting errors.
maybe due the fact that my project already exist on disk with the same name.
grafik

better send me a PR in the nono303 branch.

**Comment by nono303** [comment]
importing as an "existing gradle project" without having another project with the same name should works fine
in order to clean an simplify (as some mapsforgesrv gradle task are not shown in eclipse) can you tell me:
- what is the purpose of /app project? seems to be empty
  - if it can be removed, I purpose move a clean level up (git rename to root) mapsforve gradle project. It would be much easier to maintain 
- is the junit project nature should be kept? actually no test implemented (maybe you wait to kept it for later...)

**Comment by telemaxx** [comment]
"/app" was automaticaly created. there is no plan to use it. can be removed.

this was my 1st gradle project.
currently the structure is "mapsforgesv/mapsforgesrv".
one level up would be fine. i think i already tried that without success.
junit folder is unused.

**Pull request merged**
