### PR TITLE
global gradle refactoring

### PR DESCRIPTION
**Pull request by nono303**
https://github.com/nono303/mapsforgesrv/releases/tag/v0.21.3.0_style

### CODE REVIEW

**Comment by nono303** [comment]
hi @telemaxx,
According to https://github.com/telemaxx/mapsforgesrv/pull/64#issuecomment-2143939878 you'll find a refactored Gradle project.
 - All now is at root, removing app & testing support
 - Only change is output dir of the fatjar: `/bin/jars_ready2use` > `/dist` _(which seems to be a standard)_
I've 'played' https://github.com/nono303/mapsforgesrv/blob/styles/HOWTO.md on a windows sandbox with a fresh Eclipse & OpenJDK22 : it's works fine 🎉 

The only think I've to dig on is how to manage `sourceCompatibility` & `targetCompatibility`  for `JavaVersion.VERSION_11`
_(actually [commented](https://github.com/nono303/mapsforgesrv/blob/styles/build.gradle#L110) for my usage, but required for yours)_
 - My goal is to find a way to have a parameter (or something like this) to Gradle tasks `shadowJar` & `runShadow` specifing the targeted JRE version

So, i'll let U try on your side, give me your feedback and maybe keep this PR open until we can have a releasable version :)

**Comment by telemaxx** [comment]
sounds good. this week i am not at home, so it will take some days before i can test.

**Comment by telemaxx** [comment]
hi nono303,
i fight a hour with the PR,
at the end i deleted some branches and created a new branch `styles`
in this branch i send myself a pr of youre fork. [nono303/styles](https://github.com/nono303/mapsforgesrv/tree/styles)

i add `/dist/mapsforgesrv-fat.jar` to .gitignore

now i can start the server in the styles branch

**Comment by telemaxx** [comment]
[Discusion](https://github.com/telemaxx/mapsforgesrv/discussions/68)

**Comment by nono303** [comment]
Hi @telemaxx 
> i fight a hour with the PR,

related to conflict on the binary jar or other?
does I have to correct / enhance `HOWTO.md`
> now i can start the server in the styles branch

With the gradle task `runShadow` or manually _(eclipse run)_?
> with the use of dist is or copyFatJar2jars_ready2use deprecated, correct?

as U can see, `copyFatJar2jars_ready2use` gradle task doesn’t exist anymore
image

**Pull request merged**
