### PR TITLE
few fix & update for 0.16.6 tag & release

### PR DESCRIPTION
**Pull request by nono303**

### CODE REVIEW

**Comment by telemaxx** [comment]
this will become 0.17.0 ....

cool, that we now have to change only one line:
def mapsforgeVersion = '0.17.0'

**Comment by JFritzle** [comment]
Guess we do have to switch server version to 0.17.0 too. Don't we?

**Comment by telemaxx** [comment]
yupp, yes we do ;-)

**Comment by telemaxx** [comment]
in the master branch it is already 0.17.0

**Pull request merged**
