### PR TITLE
Styles

### PR DESCRIPTION
**Pull request by nono303**
https://github.com/telemaxx/mapsforgesrv/issues/59#issuecomment-2139429829

### CODE REVIEW

**Comment by telemaxx** [comment]
one file has some conflicts.
i think about java version 11 vs 20
our server should also run with java < v20

what do you think about?

**Comment by nono303** [comment]
that's only eclipse settings; I resolved to your own setting.
_(in my point of view, eclipse settings sould not be part of tracked files)_

**Comment by telemaxx** [comment]
seem to work with mytourbook and @JFritzle tcl script:

grafik

but i have not tested the new style parameter yet.

**Comment by telemaxx** [comment]
suddenly i got now some errors:

grafik

dummycache is also red now ?

grafik

Idea ?

**Comment by telemaxx** [comment]
I think there is also java 20 defined somewhere

grafik

Master branch:
grafik

grafik

nono303 branch:
grafik

looks different.
strange.

**Comment by telemaxx** [comment]
[Discusion](https://github.com/telemaxx/mapsforgesrv/discussions/68)

**Pull request merged**
